-- Fix RLS for teams/challenges/team_members so app can create teams/challenges again.
-- Run in Supabase SQL Editor as project owner.

begin;

-- Ensure base tables exist.
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  km double precision not null default 0,
  originator_id uuid references auth.users(id) on delete set null
);

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date timestamptz not null default now(),
  distance double precision not null,
  team_names text not null default '',
  is_active boolean not null default true,
  originator_id uuid references auth.users(id) on delete set null
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  runner_name text not null,
  created_at timestamptz not null default now()
);

-- Ensure required columns exist for policy expressions.
alter table public.teams
  add column if not exists originator_id uuid references auth.users(id) on delete set null;

alter table public.teams
  add column if not exists km double precision not null default 0;

alter table public.challenges
  add column if not exists originator_id uuid references auth.users(id) on delete set null;

alter table public.challenges
  add column if not exists is_active boolean not null default true;

alter table public.challenges
  add column if not exists team_names text not null default '';

create unique index if not exists team_members_team_user_idx
on public.team_members(team_id, user_id)
where user_id is not null;

alter table public.teams enable row level security;
alter table public.challenges enable row level security;
alter table public.team_members enable row level security;

-- Hard reset all existing policies on target tables to avoid hidden conflicts.
do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('teams', 'challenges', 'team_members')
  loop
    execute format('drop policy if exists %I on %I.%I',
      p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- Drop old/conflicting policies
-- teams
DROP POLICY IF EXISTS "teams read" ON public.teams;
DROP POLICY IF EXISTS "teams write" ON public.teams;
DROP POLICY IF EXISTS "teams_select_all" ON public.teams;
DROP POLICY IF EXISTS "teams_insert_authenticated" ON public.teams;
DROP POLICY IF EXISTS "teams_insert_any_authenticated" ON public.teams;
DROP POLICY IF EXISTS "teams_update_originator" ON public.teams;
DROP POLICY IF EXISTS "teams_delete_originator" ON public.teams;

-- challenges
DROP POLICY IF EXISTS "challenges read" ON public.challenges;
DROP POLICY IF EXISTS "challenges write" ON public.challenges;
DROP POLICY IF EXISTS "challenges_select_all" ON public.challenges;
DROP POLICY IF EXISTS "challenges_insert_authenticated" ON public.challenges;
DROP POLICY IF EXISTS "challenges_insert_any_authenticated" ON public.challenges;
DROP POLICY IF EXISTS "challenges_update_originator_active" ON public.challenges;
DROP POLICY IF EXISTS "challenges_delete_originator_active" ON public.challenges;

-- team_members
DROP POLICY IF EXISTS "read team members" ON public.team_members;
DROP POLICY IF EXISTS "insert own membership" ON public.team_members;
DROP POLICY IF EXISTS "update own membership" ON public.team_members;
DROP POLICY IF EXISTS "team_members_delete_originator" ON public.team_members;

-- Ensure table grants exist
GRANT USAGE ON schema public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.teams TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.challenges TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- teams policies
CREATE POLICY "teams_select_all"
ON public.teams
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "teams_select_public"
ON public.teams
FOR SELECT
TO public
USING (true);

CREATE POLICY "teams_insert_authenticated"
ON public.teams
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() IS NOT NULL
  AND (originator_id IS NULL OR originator_id = auth.uid())
);

-- Explicit permissive insert fallback for legacy app payloads.
CREATE POLICY "teams_insert_any_authenticated"
ON public.teams
FOR INSERT
TO public
WITH CHECK (
  true
);

CREATE POLICY "teams_update_originator"
ON public.teams
FOR UPDATE
TO authenticated
USING (
  originator_id = auth.uid()
)
WITH CHECK (
  originator_id = auth.uid()
);

CREATE POLICY "teams_delete_originator"
ON public.teams
FOR DELETE
TO authenticated
USING (
  originator_id = auth.uid()
);

-- challenges policies
CREATE POLICY "challenges_select_all"
ON public.challenges
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "challenges_select_public"
ON public.challenges
FOR SELECT
TO public
USING (true);

CREATE POLICY "challenges_insert_authenticated"
ON public.challenges
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() IS NOT NULL
  AND (originator_id IS NULL OR originator_id = auth.uid())
);

-- Explicit permissive insert fallback for legacy app payloads.
CREATE POLICY "challenges_insert_any_authenticated"
ON public.challenges
FOR INSERT
TO public
WITH CHECK (
  true
);

CREATE POLICY "challenges_update_originator_active"
ON public.challenges
FOR UPDATE
TO authenticated
USING (
  originator_id = auth.uid() AND is_active = true
)
WITH CHECK (
  originator_id = auth.uid()
);

CREATE POLICY "challenges_delete_originator_active"
ON public.challenges
FOR DELETE
TO authenticated
USING (
  originator_id = auth.uid() AND is_active = true
);

-- team_members policies
CREATE POLICY "read team members"
ON public.team_members
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "insert own membership"
ON public.team_members
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
  OR user_id IS NULL
  OR EXISTS (
    SELECT 1
    FROM public.teams t
    WHERE t.id = team_members.team_id
      AND t.originator_id = auth.uid()
  )
);

CREATE POLICY "update own membership"
ON public.team_members
FOR UPDATE
TO authenticated
USING (
  auth.uid() = user_id
  OR user_id IS NULL
  OR EXISTS (
    SELECT 1
    FROM public.teams t
    WHERE t.id = team_members.team_id
      AND t.originator_id = auth.uid()
  )
)
WITH CHECK (
  auth.uid() = user_id
  OR user_id IS NULL
  OR EXISTS (
    SELECT 1
    FROM public.teams t
    WHERE t.id = team_members.team_id
      AND t.originator_id = auth.uid()
  )
);

CREATE POLICY "team_members_delete_originator"
ON public.team_members
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.teams t
    WHERE t.id = team_members.team_id
      AND t.originator_id = auth.uid()
  )
);

commit;

notify pgrst, 'reload schema';

-- Diagnostics: verify RLS/policies exist after running this script.
select relname as table_name, relrowsecurity as rls_enabled
from pg_class
where relnamespace = 'public'::regnamespace
  and relname in ('teams', 'challenges', 'team_members')
order by relname;

select tablename, policyname, cmd, roles
from pg_policies
where schemaname = 'public'
  and tablename in ('teams', 'challenges', 'team_members')
order by tablename, policyname;
