create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  runner_name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists team_members_team_user_idx
on public.team_members(team_id, user_id)
where user_id is not null;

alter table public.team_members enable row level security;

drop policy if exists "read team members" on public.team_members;
create policy "read team members"
on public.team_members
for select
to authenticated
using (true);

drop policy if exists "insert own membership" on public.team_members;
create policy "insert own membership"
on public.team_members
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "update own membership" on public.team_members;
create policy "update own membership"
on public.team_members
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Optional backfill for existing users already registered in auth.users.
insert into public.team_members (team_id, user_id, runner_name)
select distinct
  (u.raw_user_meta_data->>'team_id')::bigint as team_id,
  u.id as user_id,
  coalesce(nullif(trim(u.raw_user_meta_data->>'runner_name'), ''), 'Anonymní běžec') as runner_name
from auth.users u
where u.raw_user_meta_data->>'team_id' is not null
on conflict (team_id, user_id)
do update set runner_name = excluded.runner_name;

-- Optional backfill for runners found only in historical activities.
insert into public.team_members (team_id, runner_name)
select distinct
  t.id as team_id,
  trim(a.runner_name) as runner_name
from public.activities a
join public.teams t
  on lower(trim(t.name)) = lower(trim(a.team_name))
where coalesce(trim(a.runner_name), '') <> ''
  and not exists (
    select 1
    from public.team_members tm
    where tm.team_id = t.id
      and lower(trim(tm.runner_name)) = lower(trim(a.runner_name))
  );